/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package org.heigit.ohsome.now.parquet.avro;
/** a combined id from osm-type(1), osm-id(8), changeset-timestamp(8), changeset-id(8) */
@org.apache.avro.specific.FixedSize(25)
@org.apache.avro.specific.AvroGenerated
public class AvroContribId extends org.apache.avro.specific.SpecificFixed {
  private static final long serialVersionUID = 4469972280326343457L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"fixed\",\"name\":\"AvroContribId\",\"namespace\":\"org.heigit.ohsome.now.parquet.avro\",\"doc\":\"a combined id from osm-type(1), osm-id(8), changeset-timestamp(8), changeset-id(8)\",\"size\":25}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }

  /** Creates a new AvroContribId */
  public AvroContribId() {
    super();
  }

  /**
   * Creates a new AvroContribId with the given bytes.
   * @param bytes The bytes to create the new AvroContribId.
   */
  public AvroContribId(byte[] bytes) {
    super(bytes);
  }

  private static final org.apache.avro.io.DatumWriter<AvroContribId>
    WRITER$ = new org.apache.avro.specific.SpecificDatumWriter<AvroContribId>(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, org.apache.avro.specific.SpecificData.getEncoder(out));
  }

  private static final org.apache.avro.io.DatumReader<AvroContribId>
    READER$ = new org.apache.avro.specific.SpecificDatumReader<AvroContribId>(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, org.apache.avro.specific.SpecificData.getDecoder(in));
  }

}
